#!/bin/bash

DATE(){
echo "[$(date +"%a %d-%m-%y %R")]"
}
BAT(){
bat=$(cat /sys/class/power_supply/BAT0/capacity)
echo "[BAT: $bat%]"
}
DISK(){
    d=$(df -h $HOME | awk '/[0-9]/ {print $3 "/" $2}')
    echo "[DISK: $d]"
}
MEM(){
    mem=$(free -m | awk '/Mem/{printf "%.2f/%.2f %s",$3/1024,$2/1024,"GB"}')
    echo "[MEM: $mem]"
}


while true; do
    xsetroot -name "$(MEM) $(DISK) $(BAT) $(DATE)"
    sleep 1m
done &

while true; do
    lowbatnotf
    sleep 2m
done &

xrandr --output DP-2 --primary --auto &
xrandr --output eDP-1 --off &  # Turn off laptop monitor

feh --bg-scale ~/pictures/wall.jpg & # Set the wallpaper

xinput disable "PS/2 Generic Mouse" & # Disable trackpoint
disable_touchpad & 	# Disable touch pad
dunst &		        # dunst for notifications
xset r rate 300 50 &	# Speed xrate up
remaps & 

unclutter &
clipmenud &             # Start clipboard manager
picom &                 # Start compositor
sxhkd &

# Startup programs
emacs --server &
syncthing -no-browser &




# Start dwm
exec dwm
