#!/bin/bash
#exec st -c ytdownloader -e
{
        source $HOME/.local/scripts/script_assets/ytlinks
	youtube-dl -f "bestaudio[ext=m4a]" -o '~/YTvids/%(playlist)s/%(title)s.%(ext)s'  --download-archive \
	$HOME/.local/scripts/script_assets/poda_dlarchive \
	--cookies $HOME/.local/scripts/script_assets/cookies.txt \
	$YTPODSA
} 2>&1 | tee ~/.local/scripts/logs/poda_log.txt
