#!/bin/bash
#exec st -c ytdownloader -e
{

	youtube-dl -f "bestvideo[height<=?360]+bestaudio/best" -o '~/YTvids/%(playlist)s/%(title)s.%(ext)s' --download-archive \
	$HOME/.local/scripts/script_assets/pdv_dlarchive \
	--cookies $HOME/.local/scripts/script_assets/cookies.txt \
	"https://www.youtube.com/playlist?list=PLT79Xr8SUlLtClkhl_AgKDTeKN9-9BsTd"
} 2>&1 | tee ~/.local/scripts/logs/pdv_log.txt

