#!/bin/bash
#exec st -c ytdownloader -e
{
        source $HOME/.local/scripts/script_assets/ytlinks    
	youtube-dl -f "bestvideo[height<=?480]+bestaudio/best" -o '~/YTvids/%(playlist)s/%(title)s.%(ext)s' --download-archive \
	$HOME/.local/scripts/script_assets/pdv_dlarchive \
	--cookies $HOME/.local/scripts/script_assets/cookies.txt \
	$YTPODSV
} 2>&1 | tee ~/.local/scripts/logs/pdv_log.txt

