#!/usr/bin/bash


battery=("Battery: $(source ~/.local/scripts/dunstnot/battery.sh)")
network=("Network: $(source ~/.local/scripts/dunstnot/network.sh)")
vpn=("VPN: $(source ~/.local/scripts/dunstnot/vpn.sh)")
timeDate=$(source ~/.local/scripts/dunstnot/timeDate.sh)
volume=("Volume: $(source ~/.local/scripts/dunstnot/volume.sh)")
corona=("Rona: $(source ~/.local/scripts/corona.sh)")
memory=("Memory: $(source ~/.local/scripts/dunstnot/memory.sh)")
storage=("Storage: $(source ~/.local/scripts/dunstnot/storage.sh)")
music=("Song: $(mocp -Q %file | cut -d '/' -f 6-7)")


notify-send -u  "Low" "Status" "$(echo -e "$battery\n$network\n$vpn\n$timeDate\n$memory\n$storage\n$volume\n$corona\n$music")"
